### ISSUE TITLE
Fails to disable the `useObjectCode` option

### ISSUE THREAD

**Issue by 553224019** [dramforever/vscode-ghc-simple#27]
## Status

- [ ] A workaround is available
- [x] A fix is written
- [x] A fix is released
- [x] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.5
- Version of VSCode: 1.32.3
- Version of Haskell-related tools:
    
    - GHC: 8.4.3
    - Stack: 1.7.1
    - Cabal: 2.2.0.0

## Steps to reproduce

It happens when I was trying to disable the option `ghcSimple.useObjectCode` and it doesn't work. I set the option to `false`, but GHCi still generates `.o` and `.hi` files in the workspace for `.hs` files while I don't want it to do that.

## Workspace

null

## Possible Fix
I looked into the code and think the problem might be in [that line](https://github.com/dramforever/vscode-ghc-simple/blob/master/src/session.ts#L84).
I changed it to that and it's OK:
```Typescript
if (vscode.workspace.getConfiguration('ghcSimple', this.workspaceFolder.uri).get('useObjectCode'))
```
There might be some similar problems in the code ( I guess

**Comment by dramforever** [comment]
> There might be some similar problems in the code (I guess)

I checked and I think there aren't.

**Comment by 553224019** [comment]
I checked it under debug mode and seemed that the problem has been fixed. Thanks!

**Comment by dramforever** [comment]
Fixed in v0.1.7. If this does not solve this or causes other problems, feel free to reopen this or create a new issue.

**Comment by turbolent** [comment]
It seems like this issue is not fixed yet. It looks like the byte-code option is added in any case: https://github.com/dramforever/vscode-ghc-simple/blob/8d2ba7c6332eece3653513c9d7d35a796453d283/src/session.ts#L105+L110

I tried to disable it to be able to use the foreign function interface, but saw in the GHCi console that the `:set -fbyte-code` is always sent, no matter if the option is enabled or disabled.

**Comment by dramforever** [comment]
This options only concerns whether `-fobject-code` is used. I always use `-fbyte-code` so that features like completion work best. I'll probably add another option to not use `-fbyte-code`.

**Comment by dramforever** [comment]
Should be fixed in v0.1.20.
